### ISSUE TITLE
possible to add an additional licence?

### ISSUE THREAD

**Issue by horst-n** [jacoka/GIFDecoder#1]
Hi @jacoka ,

would it be possible to add another licence besides the LGPL ?
One out of:

MPL 2.0
https://www.mozilla.org/en-US/MPL/2.0/

MIT
https://opensource.org/licenses/MIT

Apache
https://www.apache.org/licenses/LICENSE-2.0

would be very helpful for many OS-projects. (Same licence needs to be added to the GIFEncoder too.)

**Comment by horst-n** [comment]
is it not possible?

**Comment by jacoka** [comment]
Hi Horst,
I am sorry for the later answer, i was too busy.
I added Apache License 2.0 to the class.

**Comment by horst-n** [comment]
Yeah! :)
